language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
script:
- python3 setup.py test
before_install:
- openssl aes-256-cbc -K $encrypted_41496df54f1e_key -iv $encrypted_41496df54f1e_iv
  -in env.py.enc -out spaced_repetition/env.py -d
after_success:
- coveralls
