language: python
python:
- '3.6'
- nightly
install:
- pip install -r requirements.txt
script:
- coverage run --source=spaced_repetition setup.py test
after_success:
- coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_41496df54f1e_key -iv $encrypted_41496df54f1e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
